### ISSUE TITLE
Use preferred tile.openstreetmap.org URL

### ISSUE THREAD

**Issue by Falke-Design** [pkolmann/FFalarmPrinter#4]
https://github.com/pkolmann/FFalarmPrinter/blob/9e16304d3ff95518beff7eaac48a4a0f025b1839/template.html#L111

`https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png` -> `https://tile.openstreetmap.org/{z}/{x}/{y}.png`

Reference: https://github.com/openstreetmap/operations/issues/737

**Comment by pkolmann** [comment]
Danke @Falke-Design für den Hinweis. Hab ich eingebaut.
